# ansible-awx.yaml
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: ansible-awx
  namespace: awx
spec:
  service_type: LoadBalancer
  # Ask MetalLB for this exact IP
  service_annotations: |
    metallb.universe.tf/loadBalancerIPs: "172.16.23.39"

  # persistence (from your setup)
  postgres_storage_class: longhorn
  projects_persistence: true
  projects_storage_class: longhorn
  projects_storage_size: 10Gi
