apiVersion: v1
kind: PersistentVolume
metadata:
  name: awx-postgres-pv
  namespace: immich
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: awx-postgres-pv
